[versions]
alchemist = "33.1.1"
kotlin = "1.9.23"
scalapy = "0.5.3+2-d2eb0088"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-euclidean-geometry = {module = "it.unibo.alchemist:alchemist-euclidean-geometry", version.ref = "alchemist" }
alchemist-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist" }
alchemist-swing = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-ui-tooling = { module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
scalapy = { module = "dev.scalapy:scalapy-core_2.13", version.ref = "scalapy" }
scala-csv = { module = "com.github.tototoshi:scala-csv_2.13", version = "1.3.10"}

[bundles]
alchemist = [ "alchemist", "alchemist-scafi", "alchemist-euclidean-geometry", "alchemist-swing", "alchemist-ui-tooling" ]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.4" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.61.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.5.8" }
taskTree = { id = "com.dorongold.task-tree", version = "3.0.0" }